---
- name: Delete a test file on target host
  hosts: all
  become: false
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3.9
  tasks:
    - name: Delete the test file
      file:
        path: /tmp/ansible_managed_file.txt
        state: absent

    - name: Confirm deletion
      stat:
        path: /tmp/ansible_managed_file.txt
      register: file_check

    - name: Report result
      debug:
        msg: "File deleted successfully: {{ not file_check.stat.exists }}"
